clinic/clinic/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^refer/', include('refer.urls'))
]

clinic/refer/urls.py
from django.conf.urls import url
from . import views 

app_name = 'refer'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="details"),
    url(r'refer/add/$', views.ReferralCreate.as_view(), name='referral-add'),
]

clinic/refer/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Referral(models.Model):
    name = models.CharField(max_length=250)
    physician = models.CharField(max_length=250)
    serviceProvider = models.CharField(max_length=250)
    reason = models.CharField(max_length=250)
    date = models.CharField(max_length=250)

    def get_absolute_url(self):
        return reverse('refer:details', kwargs={'pk' : self.pk})

    def __str__(self):
        return self.name + ' - ' + self.reason

class Patient(models.Model):
    referral = models.ForeignKey(Referral, on_delete=models.CASCADE)
    history = models.CharField(max_length=1000)
    is_review = models.BooleanField(default=False)

    def __str__(self):
        return self.history

clinic/refer/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Referral

class IndexView(generic.ListView):
    template_name = 'refer/index.html'
    context_object_name = 'all_referrals'
    
    def get_queryset(self):
        return Referral.objects.all()

class DetailView(generic.DetailView):
    model = Referral
    template_name = 'refer/details.html'


class ReferralCreate(CreateView):
    model = Referral
    fields = ['name', 'physician', 'serviceProvider', 'reason', 'date']

clinic/refer/templates/refer/base.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset="UTF-8">
        {% block title %}<title>Sarasota Family Medical</title>{% endblock %}
    
        {% load staticfiles %}
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet"><link rel="preconnect" href="https://fonts.gstatic.com"><link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'refer/images/style.css' %}" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>
    
    <body>

        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
        
                <!-- Header -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'refer:index' %}">Sarasota Family</a>
                </div>
        
                <!-- Items-->
                <div class="collapse navbar-collapse" id="topNavBar">
        
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="{% url 'refer:index' %}">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp;
                                Referrals
                            </a>
                        </li>
                        <li class="">
                            <a href="{% url 'refer:index' %}">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp;
                                Ultrasounds
                            </a>
                        </li>
                        <li class="">
                            <a href="{% url 'refer:index' %}">
                                <span class="glyphicon glyphicon-sunglasses" aria-hidden="true"></span>&nbsp;
                                Patients
                            </a>
                        </li>
                    </ul>
        
                    <form class="navbar-form navbar-left" role="search" method="get" action="">
                        <div class="form-group">
                            <input type="text" class="form-control" name="q" value="">
                            <button type="submit" class="btn btn-default">Search</button>
                        </div>
                    </form>
        
                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="{% url 'refer:referral-add' %}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                                Add Referral
                            </a>
                        </li>
                        <li class="">
                            <a href="{% url 'refer:index' %}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                                Add Ultrasound
                            </a>
                        </li>
                        <li class="">
                            <a href="{% url 'refer:index' %}">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                                Logout
                            </a>
                        </li>
        
                    </ul>
                </div>
            </div>
        </nav>

    </body>
    {% block body %}
    {% endblock %}
</html>

clinic/refer/templates/refer/details.html
{% extends 'refer/base.html' %}
{% block title %}<title>Referrals</title>{% endblock %}

{% block body %}

    <h1>{{referral}}</h1>
    <br>
        {%for patient in referral.patient_set.all %}
            {{patient.history}}
        <br>
        {% endfor %}
    
{% endblock %}

clinic/refer/templates/refer/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{field}}</div>
    </div>
{% endfor %}

clinic/refer/templates/refer/index.html
{% extends 'refer/base.html' %}


{% block body %}

<body>

    <div class="container">
      <h2>Contextual Classes</h2>
      <p>Contextual classes can be used to color table rows or table cells. The classes that can be used are: .active, .success, .info, .warning, and .danger.</p>
      <table class="table">
        <thead>
          <tr>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Default</td>
            <td>Defaultson</td>
            <td>def@somemail.com</td>
          </tr>      
          <tr class="success">
            <td>Success</td>
            <td>Doe</td>
            <td>john@example.com</td>
          </tr>
          <tr class="danger">
            <td>Danger</td>
            <td>Moe</td>
            <td>mary@example.com</td>
          </tr>
          <tr class="info">
            <td>Info</td>
            <td>Dooley</td>
            <td>july@example.com</td>
          </tr>
          <tr class="warning">
            <td>Warning</td>
            <td>Refs</td>
            <td>bo@example.com</td>
          </tr>
          <tr class="active">
            <td>Active</td>
            <td>Activeson</td>
            <td>act@example.com</td>
          </tr>
        </tbody>
      </table>
    </div>
    
    </body>
     


{% endblock %}

clinic/refer/templates/refer/referral_form.html
{% extends 'refer/base.html' %}
{% block title %}Add a New Referral{% endblock %}

{% block body %}
<div class='container-fluid'>

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'refer/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>


                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}